[start]
plugins = [
	nvim-treesitter,
	catppuccin-nvim,
]
parsers = [
	r,
	c,
	go,
	lua,
	nix,
	zig,
	vue,
	tsx,
	sql,
	php,
	csv,
	css,
	cpp,
	scss,
	toml,
	sway,
	yaml,
	rust,
	ruby,
	json,
	java,
	html,
	bash,
	typst,
	scala,
	ocaml,
	latex,
	gosum,
	gomod,
	cmake,
	python,
	pascal,
	bibtex,
	mermaid,
	haskell,
	gnuplot,
	doxygen,
	arduino,
	markdown,
	hyprlang,
	gitignore,
	gitcommit,
	typescript,
	javascript,
	dockerfile,
	git_config,
	gitatttibutes,
]

[opt]
plugins = [
	vim-fern,
	telescope-nvim,
	telescope-github-nvim,
]
